-- Staging for category (product category master data).
-- Databricks reads the real ust_databricks.mysql.category table; DuckDB reads
-- mock parquet (data/mock/mysql/ust_category.parquet, generated by
-- scripts/generate_jdawms_mock.py from seed_categories) via the source's
-- external_location.

with source as (

    select * from {{ source('mysql', 'category') }}

)

select
    cast(category_id as bigint)                                                        as entity_id,
    cast(nullif(trim(cast(parent_id     as {{ dbt.type_string() }})), '') as bigint)   as parent_id,
    nullif(trim(cast(name               as {{ dbt.type_string() }})), '')              as category_name,
    nullif(trim(cast(is_active          as {{ dbt.type_string() }})), '')              as is_active,
    try_cast(nullif(trim(cast(position      as {{ dbt.type_string() }})), '') as bigint) as position,
    try_cast(nullif(trim(cast(level         as {{ dbt.type_string() }})), '') as bigint) as category_level,
    try_cast(nullif(trim(cast(product_count as {{ dbt.type_string() }})), '') as bigint) as product_count,
    nullif(trim(cast(meta_title         as {{ dbt.type_string() }})), '')              as meta_title,
    nullif(trim(cast(meta_keywords      as {{ dbt.type_string() }})), '')              as meta_keywords,
    nullif(trim(cast(meta_description   as {{ dbt.type_string() }})), '')              as meta_description,
    cast(nullif(trim(cast(create_at     as {{ dbt.type_string() }})), '') as timestamp) as created_at,
    cast(nullif(trim(cast(updated_at    as {{ dbt.type_string() }})), '') as timestamp) as updated_at
from source
