-- Staging for admin_users (salesperson + admin master data).
-- Databricks reads the real ust_databricks.mysql.admin_users table; DuckDB
-- reads mock parquet (data/mock/mysql/ust_admin_users.parquet, generated by
-- scripts/generate_jdawms_mock.py) via the source's external_location.

with source as (

    select * from {{ source('mysql', 'admin_users') }}

)

select
    cast(user_id as bigint)                                                                as user_id,
    nullif(trim(cast(username             as {{ dbt.type_string() }})), '')                as username,
    nullif(trim(cast(firstname            as {{ dbt.type_string() }})), '')                as first_name,
    nullif(trim(cast(lastname             as {{ dbt.type_string() }})), '')                as last_name,
    nullif(trim(cast(email                as {{ dbt.type_string() }})), '')                as email,
    nullif(trim(cast(salesperson_code     as {{ dbt.type_string() }})), '')                as salesperson_code,
    nullif(trim(cast(role_name            as {{ dbt.type_string() }})), '')                as role_name,
    nullif(trim(cast(interface_locale     as {{ dbt.type_string() }})), '')                as interface_locale,
    try_cast(nullif(trim(cast(is_active            as {{ dbt.type_string() }})), '') as bigint) as is_active,
    try_cast(nullif(trim(cast(is_salesperson       as {{ dbt.type_string() }})), '') as bigint) as is_salesperson,
    try_cast(nullif(trim(cast(convert_quotes       as {{ dbt.type_string() }})), '') as bigint) as convert_quotes,
    try_cast(nullif(trim(cast(receive_quote_emails as {{ dbt.type_string() }})), '') as bigint) as receive_quote_emails,
    try_cast(nullif(trim(cast(lognum               as {{ dbt.type_string() }})), '') as bigint) as lognum,
    cast(nullif(trim(cast(logdate         as {{ dbt.type_string() }})), '') as timestamp)   as logdate,
    cast(nullif(trim(cast(created         as {{ dbt.type_string() }})), '') as timestamp)   as created_at,
    cast(nullif(trim(cast(modified        as {{ dbt.type_string() }})), '') as timestamp)   as updated_at
from source
