-- Staging for jdawms.pckwrk_dtl — 1:1 lossless view over the raw WMS replica.
-- All 53 source columns preserved as-is (types already clean in Delta).
-- Databricks-only (no local sample); materialized as a view (see dbt_project.yml).

with source as (
    select * from {{ source('jdawms', 'pckwrk_dtl') }}
)

select
    wrkref_dtl,
    wrkref,
    cmbcod,
    wh_id,
    client_id,
    dstloc,
    dst_mov_zone_id,
    ship_line_id,
    ship_id,
    ordnum,
    ordlin,
    ordsln,
    stcust,
    rtcust,
    concod,
    pckqty,
    pck_catch_qty,
    appqty,
    app_catch_qty,
    lodlvl,
    ship_ctncod,
    ship_ctnnum,
    wkonum,
    wkorev,
    wkolin,
    seqnum,
    subnum,
    dtlnum,
    subucc,
    subtag,
    cur_cas,
    tot_cas_cnt,
    prtdte,
    bto_seqnum,
    slot,
    bto_dlv_seq,
    lm_assign_num,
    lm_assign_seqnum,
    pm_err_cod,
    pm_err_desc,
    ctnerr_flg,
    res_uom,
    ins_dt,
    last_upd_dt,
    ins_user_id,
    last_upd_user_id,
    rowid,
    schbat,
    untcas,
    wrktyp,
    prtnum,
    prt_client_id,
    loaddate
from source
