-- Staging for jdawms.shipment — 1:1 lossless view over the raw WMS replica.
-- All 75 source columns preserved as-is (types already clean in Delta).
-- Databricks reads the real replica; DuckDB reads mock parquet (see data/README.md).

with source as (
    select * from {{ source('jdawms', 'shipment') }}
)

select
    ship_id,
    wh_id,
    host_client_id,
    host_ext_id,
    shpsts,
    stop_id,
    rt_adr_id,
    cargrp,
    carcod,
    srvlvl,
    sddflg,
    doc_num,
    track_num,
    mst_waybill,
    frtchg,
    frtcod,
    frtrte,
    adddte,
    alcdte,
    stgdte,
    loddte,
    entdte,
    early_shpdte,
    late_shpdte,
    early_dlvdte,
    late_dlvdte,
    dstloc,
    rrlflg,
    wave_set,
    tms_group_id,
    tms_move_id,
    tms_move_plan_id,
    lst_prtdte,
    super_ship_id,
    super_ship_flg,
    in_transit_flg,
    pln_shpsts,
    ses_grp_nam,
    optm_base_cost,
    rate_serv_nam,
    arcdte,
    arc_src,
    lbl_prtdte,
    ses_tag,
    price_sts,
    src_sys,
    par_ship_id,
    hub_adr_id,
    hub_arrdte,
    zs_line_haul_id,
    hub_rate_serv_nam,
    tot_pkg_qty,
    crncy_code,
    aesitn,
    aes_typ,
    aes_acpt_dte,
    ftsrnum,
    export_typ,
    docind,
    descgoods,
    exprsntxt,
    pack_code,
    pln_cmpl_flg,
    dispatch_code,
    moddte,
    mod_usr_id,
    book_num,
    dst_mov_zone_id,
    bola_num,
    dlv_dte,
    pod_conf_flg,
    dlvseq_load_order,
    wa_rule_reference,
    _rescued_data,
    loaddate
from source
