-- Staging for jdawms.dlytrn — 1:1 lossless view over the raw WMS replica.
-- All 105 source columns preserved as-is (types already clean in Delta).
-- Cross-source join keys (prtnum, prt_client_id) are whitespace-trimmed to
-- match the trimmed MySQL side; WMS CHAR columns can be space-padded.
-- Databricks reads the real replica; DuckDB reads mock parquet (see data/README.md).

with source as (
    select * from {{ source('jdawms', 'dlytrn') }}
)

select
    dlytrn_id,
    trndte,
    oprcod,
    actcod,
    lodnum,
    subnum,
    dtlnum,
    to_lodnum,
    to_subnum,
    to_dtlnum,
    trim(prtnum) as prtnum,
    trim(prt_client_id) as prt_client_id,
    orgcod,
    revlvl,
    lotnum,
    sup_lotnum,
    supnum,
    inv_attr_str1,
    inv_attr_str2,
    inv_attr_str3,
    inv_attr_str4,
    inv_attr_str5,
    inv_attr_str6,
    inv_attr_str7,
    inv_attr_str8,
    inv_attr_str9,
    inv_attr_str10,
    inv_attr_str11,
    inv_attr_str12,
    inv_attr_str13,
    inv_attr_str14,
    inv_attr_str15,
    inv_attr_str16,
    inv_attr_str17,
    inv_attr_str18,
    inv_attr_int1,
    inv_attr_int2,
    inv_attr_int3,
    inv_attr_int4,
    inv_attr_int5,
    inv_attr_flt1,
    inv_attr_flt2,
    inv_attr_flt3,
    inv_attr_dte1,
    inv_attr_dte2,
    movref,
    reacod,
    trnqty,
    catch_qty,
    traknm,
    catch_unttyp,
    fr_arecod,
    frstol,
    frinvs,
    fr_age_pflnam,
    to_arecod,
    tostol,
    toinvs,
    to_age_pflnam,
    trlr_num,
    trct_num,
    carcod,
    ship_id,
    client_id,
    ordnum,
    trndtl_id,
    trndtl_table,
    adj_ref1,
    adj_ref2,
    usr_id,
    devcod,
    arcdte,
    arc_src,
    cmnt,
    asset_typ,
    asset_id,
    asset_stat,
    load_attr1_flg,
    load_attr2_flg,
    load_attr3_flg,
    load_attr4_flg,
    load_attr5_flg,
    var_nam,
    fr_value,
    to_value,
    wh_id,
    uomcod,
    ftpcod,
    distro_excp_id,
    excp_code,
    expqty,
    rptqty,
    u_version,
    ins_dt,
    last_upd_dt,
    ins_user_id,
    last_upd_user_id,
    to_trct_num,
    to_trlr_num,
    to_carcod,
    srvlvl,
    to_srvlvl,
    rowid,
    _rescued_data,
    loaddate
from source
