"""Regenerate value-level {% docs %} glossary blocks for the reference seeds so
their code -> definition tables render on the dbt docs seed pages.

Reads the seed CSVs and (over)writes a single owned file:
    models/docs/_seed_value_glossaries.md

Each block is referenced from seeds/_seeds.yml via {{ doc("<name>_glossary") }}.
This file is fully machine-owned — do not edit by hand; re-run after any seed
change:  python scripts/generate_seed_value_glossaries.py

Kept separate from _seed_glossaries.md (which generate_event_glossary.py owns)
so the two generators never clobber each other.
"""
import csv, os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEEDS = os.path.join(REPO, "seeds")
OUT = os.path.join(REPO, "models", "docs", "_seed_value_glossaries.md")

def rows(name):
    with open(os.path.join(SEEDS, name), encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))

def cell(v):
    """Make a value safe inside a markdown table cell."""
    s = "" if v is None else str(v)
    return s.replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()

def table(headers, body_rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in body_rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)

def block(name, title, intro, body):
    return f"{{% docs {name} %}}\n{title}\n\n{intro}\n\n> Auto-generated from the seed CSV by `scripts/generate_seed_value_glossaries.py` — do not edit by hand.\n\n{body}\n{{% enddocs %}}\n"

blocks = []

# ---- 1) jdawms code descriptions (grouped by code_domain) ----
jd = rows("seed_jdawms_code_descriptions.csv")
domains = {}
for r in jd:
    domains.setdefault(r["code_domain"], []).append(r)
parts = []
for dom in sorted(domains):
    drows = sorted(domains[dom], key=lambda r: r["code_value"])
    parts.append(f"### `{dom}` ({len(drows)})\n\n" +
                 table(["Code value", "Long description", "Short description"],
                       [(r["code_value"], r["long_description"], r["short_description"]) for r in drows]))
blocks.append(block("jdawms_code_descriptions_glossary",
    "JDA/Blue Yonder WMS coded-value dictionary",
    f"One row per (code_domain, code_value); {len(jd)} values across {len(domains)} domains. Verbatim, sic.",
    "\n\n".join(parts)))

# ---- 2) category name aliases (grouped by alias_type) ----
al = rows("seed_category_name_aliases.csv")
by_type = {}
for r in al:
    by_type.setdefault(r["alias_type"], []).append(r)
parts = []
for t in sorted(by_type):
    trows = sorted(by_type[t], key=lambda r: r["raw_name"].lower())
    parts.append(f"### `{t}` ({len(trows)})\n\n" +
                 table(["Raw name", "category_id", "Definition"],
                       [(r["raw_name"], r["category_id"], r["dev_definition"]) for r in trows]))
blocks.append(block("category_name_aliases_glossary",
    "categories_name -> category mapping / classification",
    f"{len(al)} observed raw strings, classified by alias_type. Only category_match / "
    "aggregate_view_all carry a category_id; the rest flow downstream tagged for routing "
    "(search_query, brand_keyword, ui_label, error_payload).",
    "\n\n".join(parts)))

# ---- 3) layout codes ----
lc = rows("seed_layout_codes.csv")
blocks.append(block("layout_codes_glossary",
    "user_activity_report_event.layout codes",
    "Catalog viewing-layout codes (dev team 2026-07-22).",
    table(["Code", "Layout", "Notes"], [(r["layout_code"], r["layout_name"], r["notes"]) for r in lc])))

# ---- 4) warn event codes ----
wc = rows("seed_warn_event_codes.csv")
blocks.append(block("warn_event_codes_glossary",
    "WARN-level system_event_log codes",
    f"{len(wc)} description_codes that fire at the WARN log level (network-layer errors); "
    "filter events on these to drop error-string noise. See error_payload rows in "
    "seed_category_name_aliases.",
    table(["description_code", "log_level", "Notes"],
          [(r["description_code"], r["log_level"], r["notes"]) for r in wc])))

# ---- 5) app category codes ----
ac = rows("seed_app_category_codes.csv")
blocks.append(block("app_category_codes_glossary",
    "App Category Code Dictionary",
    "Decodes category codes the apps write into payloads. real_category rows alias a website "
    "category (join ust_category_id); virtual_slot rows are home-page sections/feeds, not "
    "product categories.",
    table(["app_category_code", "app_id", "ust_category_id", "category_name", "icon", "code_type", "notes"],
          [(r["app_category_code"], r["app_id"], r["ust_category_id"], r["category_name"],
            r.get("icon", ""), r["code_type"], r.get("notes", "")) for r in ac])))

header = ("<!-- Auto-generated by scripts/generate_seed_value_glossaries.py — DO NOT EDIT BY HAND. -->\n"
          "<!-- Value-level dictionaries for the reference seeds; referenced from seeds/_seeds.yml. -->\n\n")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(header + "\n\n".join(blocks))

print("wrote", os.path.relpath(OUT, REPO))
print(f"  jdawms={len(jd)} rows / {len(domains)} domains | aliases={len(al)} | "
      f"layout={len(lc)} | warn={len(wc)} | app_category={len(ac)}")
